spring:
  application:
    name: logicsphere-cosmos-core

  datasource:
    url: jdbc:postgresql://localhost:5432/ls_cosmos
    username: cosmos
    password: cosmos2k20

  cloud:
    zookeeper:
      enabled: false

    consul:
      enabled: false

  flyway:
    enabled: true

  zipkin:
    enabled: false

---
spring:
  profiles: debug

  jpa:
    show-sql: true
    properties:
      hibernate.format_sql: true

---
spring:
  profiles: tests

  datasource:
    url: jdbc:postgresql://localhost:5432/ls_cosmos_test

  cloud:
    zookeeper:
      enabled: false

    consul:
      enabled: false
