spring:
  application:
    name: logicsphere-cosmos-core

  profiles: development, tests

  datasource:
    url: jdbc:postgresql://localhost:5432/ls_cosmos
    username: cosmos
    password: cosmos2k20

  cloud:
    zookeeper:
      enabled: false

  flyway:
    enabled: true

---
spring:
  profiles: tests

  datasource:
    url: jdbc:postgresql://localhost:5432/ls_cosmos_test

  cloud:
    zookeeper:
      enabled: false

    consul:
      enabled: false
